apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: aks-coder-flux-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/martinbasinski/aks-coder-flux-app
  branch: main
  ref:
    branch: main
  secretRef:
    name: flux-system