apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coder-test-flux
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/coder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: coder-test-flux