apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: coder-test-flux
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/coder
  prune: true
  sourceRef:
    kind: GitRepository
    name: aks-coder-flux-app
    namespace: flux-system